import assert from 'node:assert/strict';
import { identificationSchema, summarizeListings, safeUrl, deepseek, deepseekWebSearch, parsePublicListings, research } from '../server/core.mjs';
const identification = identificationSchema.parse({title:'Batman #125',type:'comic',confidence:.8,explanation:'Texto visible'});
assert.equal(identification.franchise,'');
assert.equal(safeUrl('javascript:alert(1)'),null);
assert.deepEqual(summarizeListings([{price:10,currency:'EUR',shipping:2},{price:20,currency:'EUR',shipping:0}]),{kind:'asking',currency:'EUR',count:2,min:12,max:20,median:16,label:'Precios solicitados en anuncios públicos; suma el envío cuando aparece. No son ventas cerradas.'});
const fakeFetch=async()=>new Response(JSON.stringify({choices:[{message:{content:'{"summary":"Ficha contrastada","facts":[],"comparableIds":[]}'}}]}),{status:200,headers:{'content-type':'application/json'}});
assert.equal((await deepseek([{role:'user',content:'test'}],{key:'test',fetcher:fakeFetch})).summary,'Ficha contrastada');
const webFetch=async()=>new Response(JSON.stringify({content:[{type:'web_search_tool_result',content:[{type:'web_search_result',title:'Figura Batman 24,99 €',url:'https://www.ebay.es/itm/123',cited_text:'Figura Batman 24,99 €'}]}]}),{status:200,headers:{'content-type':'application/json'}});
const webSources=await deepseekWebSearch('Batman',{key:'test',fetcher:webFetch});
assert.equal(webSources.length,1);assert.equal(parsePublicListings(webSources)[0].price,24.99);
const noSources=await research({confirmed:true,item:{title:'Batman #125',type:'comic'}},{key:'test',fetcher:fakeFetch});
assert.equal(noSources.sources.length,0);assert.equal(noSources.warnings.length,1);assert.equal(noSources.sold.available,false);
console.log('core tests ok');
