import assert from 'node:assert/strict';
import {readHobbyDb,validateGuide} from '../server/hobbydb.mjs';
import {research} from '../server/core.mjs';
const item={character:'Cruella De Vil',popNumber:'1663',funkoVariant:'Chase'};
const result={status:'ok',character:item.character,popNumber:'1663',variant:'Chase',brand:'Funko',series:'Pop! Disney',url:'https://www.hobbydb.com/marketplaces/hobbydb/catalog_items/test-chase',priceGuideClicked:true,amount:37,currency:'USD',evidence:'$37 Estimated Value'};
assert.match(validateGuide(result,item).description,/Estimated Value \$37.00/);
for(const change of [{variant:'Classic'},{priceGuideClicked:false},{amount:45},{status:'blocked'},{url:'https://hobbydb.com.evil.test/marketplaces/hobbydb/catalog_items/test'},{evidence:'For Sale or Trade $37'}])assert.throws(()=>validateGuide({...result,...change},item));
const calls=[];
const fake=async(url,init)=>{calls.push([url,init]);return Response.json(url.includes('run-async')?{run_id:'test-run'}:url.endsWith('/cancel')?{status:'CANCELLED'}:{status:'RUNNING',steps:[{action:'CAPTCHA challenge'}]});};
await assert.rejects(()=>readHobbyDb(item,{key:'test',fetcher:fake,wait:async()=>{}}),/intervención/);
assert.ok(calls.at(-1)[0].endsWith('/cancel'));
assert.equal(calls.filter(([url])=>url.includes('run-async')).length,1);
const success=async url=>Response.json(url.includes('run-async')?{run_id:'ok-run'}:{status:'COMPLETED',result});
assert.match((await readHobbyDb(item,{key:'test',fetcher:success})).description,/\$37.00/);
const researched=await research({confirmed:true,item:{...item,type:'funko',title:'Cruella De Vil #1663 Chase',manufacturer:'Funko',line:'Pop! Disney'}},{hobbyDbReader:async()=>validateGuide(result,item),fetcher:async url=>Response.json(String(url).includes('frankfurter.dev')?{rate:.9}:{rates:{EUR:.9}})});
assert.equal(researched.asking.originalMedian,37);
assert.equal(researched.asking.originalCurrency,'USD');
assert.equal(researched.asking.median,33.3);
console.log('hobbydb tests ok');
