const HOBBYDB='https://www.hobbydb.com';

function json(res,status,body){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(body));}
function normalize(value){return String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();}
function numberToken(value){return String(value||'').match(/\d{1,5}/)?.[0]||'';}
function requestedVariant(item){const raw=normalize(item.funkoVariant||'');if(!raw||['classic','standard','regular','normal'].includes(raw))return'classic';if(raw.includes('chase'))return'chase';if(raw.includes('flocked'))return'flocked';if(raw.includes('glow')||raw.includes('gitd'))return'glow';if(raw.includes('metallic'))return'metallic';if(raw.includes('diamond'))return'diamond';if(raw.includes('black light'))return'black light';if(raw.includes('chrome'))return'chrome';return raw;}
function variantLabel(value){return value==='classic'?'Classic':value==='glow'?'Glow in the Dark':value==='black light'?'Black Light':value.charAt(0).toUpperCase()+value.slice(1);}
function rowVariant(attrs){const hay=normalize([attrs?.aka,attrs?.variant_details_summary,attrs?.variant_group_name,...(Array.isArray(attrs?.production_status)?attrs.production_status:[])].filter(Boolean).join(' '));if(/\bchase\b/.test(hay))return'chase';if(/\bflocked\b/.test(hay))return'flocked';if(/\bglow in the dark\b|\bgitd\b/.test(hay))return'glow';if(/\bmetallic\b/.test(hay))return'metallic';if(/\bdiamond\b/.test(hay))return'diamond';if(/\bblack light\b/.test(hay))return'black light';if(/\bchrome\b/.test(hay))return'chrome';return'classic';}
async function hobbydbFetch(path,cookie,accept='application/json'){const response=await fetch(path.startsWith('http')?path:HOBBYDB+path,{method:'GET',headers:{Accept:accept,Cookie:cookie,'User-Agent':'Mozilla/5.0 FrikiVault/1.0',Referer:HOBBYDB+'/marketplaces/hobbydb'},redirect:'follow',cache:'no-store',signal:AbortSignal.timeout(15000)});if(response.status===401||response.status===403){const error=new Error('La sesión de hobbyDB ha caducado.');error.code='SESSION_EXPIRED';throw error;}if(!response.ok)throw new Error(`hobbyDB HTTP ${response.status}`);return response;}
function exactRow(item,row){const a=row?.attributes||{};const wantedName=normalize(item.character);const hayName=normalize([a.name,a.variant_group_name,...(a.related_subjects||[]).map(x=>x?.name)].filter(Boolean).join(' '));const brands=(a.brand||[]).map(x=>normalize(x?.name));const wantedNumber=String(item.popNumber||'').trim();const actualNumber=numberToken(a.ref_number);const wantedVariant=requestedVariant(item);const actualVariant=rowVariant(a);if(wantedName&&!hayName.includes(wantedName))return null;if(wantedNumber&&actualNumber!==wantedNumber)return null;if(brands.length&&!brands.includes('funko'))return null;if(wantedVariant!==actualVariant)return null;let score=0;if(normalize(a.name)===wantedName)score+=80;else if(hayName.includes(wantedName))score+=55;if(actualNumber===wantedNumber)score+=100;if(brands.includes('funko'))score+=30;if(actualVariant===wantedVariant)score+=50;return{row,score,variant:actualVariant};}
function rowUrl(row){const a=row?.attributes||{};const raw=a?.urls?.catalog_item_link_url||a?.urls?.show_url||(a.slug?`/marketplaces/hobbydb/catalog_items/${a.slug}`:'');return raw?new URL(raw,HOBBYDB).href:'';}
async function searchCatalog(query,cookie){const p=new URLSearchParams();p.set('include_cit','true');p.set('include_last_page','true');p.set('include_main_images','true');p.set('per','12');p.set('from_index','true');p.set('serializer','CatalogItemPudbSerializer');p.set('market_id','hobbydb');p.set('order[name]','created_at');p.set('order[sort]','desc');p.set('page','1');p.set('q',query);p.set('subvariants','true');p.set('grouped','false');const response=await hobbydbFetch(`/api/catalog_items?${p.toString()}`,cookie);const payload=await response.json();return Array.isArray(payload?.data)?payload.data:[];}
function urlHint(item){try{const u=new URL(item.hobbydbUrl||'');if(!['hobbydb.com','www.hobbydb.com'].includes(u.hostname))return{};const slug=u.pathname.match(/\/marketplaces\/hobbydb\/catalog_items\/([^/?#]+)/i)?.[1]||'';const q=u.searchParams.get('q')||'';return{slug,q};}catch{return{};}}
async function resolveItem(item,cookie){const wanted=requestedVariant(item);const hint=urlHint(item);const queries=[hint.q,[item.character,item.popNumber,wanted==='classic'?'':item.funkoVariant].filter(Boolean).join(' '),[item.character,item.popNumber].filter(Boolean).join(' '),[item.character,wanted==='classic'?'':item.funkoVariant].filter(Boolean).join(' '),String(item.character||'').trim(),String(item.popNumber||'').trim()].map(x=>String(x||'').trim()).filter(Boolean);const unique=[...new Set(queries)];const seen=new Map();for(const query of unique){let rows=[];try{rows=await searchCatalog(query,cookie);}catch(error){if(error?.code==='SESSION_EXPIRED')throw error;continue;}for(const row of rows){if(row?.id&&!seen.has(String(row.id)))seen.set(String(row.id),row);}const exact=[...seen.values()].map(row=>exactRow(item,row)).filter(Boolean);if(exact.length){exact.forEach(x=>{if(hint.slug&&rowUrl(x.row).includes(`/catalog_items/${hint.slug}`))x.score+=150;});exact.sort((a,b)=>b.score-a.score);const best=exact[0];const a=best.row.attributes||{};return{id:String(best.row.id||a.id),url:rowUrl(best.row),title:a.name||item.character,variant:best.variant,searchEstimatedValue:Number(a.estimated_value)||null};}}
 throw new Error('No se encontró una ficha de hobbyDB que coincida exactamente con nombre, número y variante.');}
async function readPriceGuide(catalogItemId,cookie){const response=await hobbydbFetch(`/api/price_guide?catalog_item_id=${encodeURIComponent(catalogItemId)}`,cookie);const payload=await response.json();const attributes=payload?.data?.[0]?.attributes;const amount=Number(attributes?.estimated_value);if(!Number.isFinite(amount)||amount<=0)return null;return{amount,currency:'USD',timestamp:attributes?.timestamp||null,calculatedFor:attributes?.calculated_for||null};}
export default async function handler(req,res){const origin=String(req.headers.origin||'');const allowedOrigin=String(process.env.APP_ORIGIN||'').replace(/\/$/,'');if(origin&&allowedOrigin&&origin!==allowedOrigin)return json(res,403,{error:'Origen no autorizado.'});if(origin&&allowedOrigin)res.setHeader('Access-Control-Allow-Origin',allowedOrigin);res.setHeader('Access-Control-Allow-Headers','Content-Type');res.setHeader('Access-Control-Allow-Methods','POST, OPTIONS');if(req.method==='OPTIONS')return res.status(204).end();if(req.method!=='POST')return json(res,405,{error:'Método no permitido.'});try{const cookie=String(process.env.HOBBYDB_COOKIE||'').trim();if(!cookie)return json(res,503,{error:'La sesión de hobbyDB no está configurada.'});const body=typeof req.body==='string'?JSON.parse(req.body):(req.body||{});const item=body.item||{};if(!item.character||!/^\d{1,5}$/.test(String(item.popNumber||'')))return json(res,400,{error:'Faltan personaje o número Pop.'});const match=await resolveItem(item,cookie);const guide=await readPriceGuide(match.id,cookie);const fallback=Number(match.searchEstimatedValue);const amount=guide?.amount||(Number.isFinite(fallback)&&fallback>0?fallback:null);if(!amount)return json(res,404,{error:'Sin valor publicado en hobbyDB.'});return json(res,200,{status:'completed',value:{amount,currency:'USD',url:match.url,evidence:`Estimated Value $${amount}`,variant:variantLabel(match.variant),title:match.title,catalogItemId:match.id,timestamp:guide?.timestamp||null,calculatedFor:guide?.calculatedFor||null}});}catch(error){const message=String(error?.message||'No se pudo leer hobbyDB.');const status=error?.code==='SESSION_EXPIRED'?401:502;return json(res,status,{error:message});}}
