const HOBBYDB='https://www.hobbydb.com';

function json(res,status,body){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(body));}
function normalize(value){return String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();}
function numberToken(value){return String(value||'').match(/\d{1,5}/)?.[0]||'';}
function tokens(value){return normalize(value).split(' ').filter(x=>x.length>=2);}
function categorySearchTerm(value){const raw=normalize(value);if(!raw)return'';if(raw.includes('kinder')||raw.includes('promotional'))return'Kinder';if(raw.includes('bitty'))return'Bitty';if(raw.includes('pocket'))return'Pocket';if(raw.includes('mystery mini'))return'Mystery Minis';if(raw.includes('soda'))return'Funko Soda';if(raw.includes('rides'))return'Rides';if(raw.includes('town'))return'Town';if(raw.includes('moment'))return'Moments';if(raw.includes('cover'))return'Covers';if(raw.includes('pack'))return'Pack';if(raw.includes('super'))return'Super';if(raw.includes('jumbo'))return'Jumbo';if(raw.includes('mega'))return'Mega';return String(value||'').trim();}
function requestedVariant(item){const raw=normalize(item.funkoVariant||'');if(!raw||['classic','standard','regular','normal','base'].includes(raw))return'classic';if(raw.includes('upside down'))return'upside down';if(raw.includes('chase'))return'chase';if(raw.includes('flocked'))return'flocked';if(raw.includes('glow')||raw.includes('gitd'))return'glow';if(raw.includes('metallic'))return'metallic';if(raw.includes('diamond'))return'diamond';if(raw.includes('black light'))return'black light';if(raw.includes('chrome'))return'chrome';if(raw.includes('clear')||raw.includes('translucent'))return'clear';if(raw.includes('scented'))return'scented';if(raw.includes('patina'))return'patina';if(raw.includes('wood'))return'wood deco';if(raw==='diy'||raw.includes('do it yourself'))return'diy';if(raw.includes('art series'))return'art series';return raw;}
function variantLabel(value){return value==='classic'?'Classic':value==='glow'?'Glow in the Dark':value==='black light'?'Black Light':value==='upside down'?'Upside Down':value==='wood deco'?'Wood Deco':value==='art series'?'Art Series':value.charAt(0).toUpperCase()+value.slice(1);}
function rowVariant(attrs){const hay=normalize([attrs?.name,attrs?.aka,attrs?.variant_details_summary,attrs?.variant_group_name,...(Array.isArray(attrs?.production_status)?attrs.production_status:[])].filter(Boolean).join(' '));if(/\bupside down\b/.test(hay))return'upside down';if(/\bchase\b/.test(hay))return'chase';if(/\bflocked\b/.test(hay))return'flocked';if(/\bglow in the dark\b|\bgitd\b/.test(hay))return'glow';if(/\bmetallic\b/.test(hay))return'metallic';if(/\bdiamond\b/.test(hay))return'diamond';if(/\bblack light\b/.test(hay))return'black light';if(/\bchrome\b/.test(hay))return'chrome';if(/\bclear\b|\btranslucent\b/.test(hay))return'clear';if(/\bscented\b/.test(hay))return'scented';if(/\bpatina\b/.test(hay))return'patina';if(/\bwood deco\b|\bwooden\b/.test(hay))return'wood deco';if(/\bdiy\b|\bdo it yourself\b/.test(hay))return'diy';if(/\bart series\b/.test(hay))return'art series';return'classic';}
async function hobbydbFetch(path,cookie,accept='application/json'){const response=await fetch(path.startsWith('http')?path:HOBBYDB+path,{method:'GET',headers:{Accept:accept,Cookie:cookie,'User-Agent':'Mozilla/5.0 FrikiVault/1.0',Referer:HOBBYDB+'/marketplaces/hobbydb'},redirect:'follow',cache:'no-store',signal:AbortSignal.timeout(15000)});if(response.status===401||response.status===403){const error=new Error('La sesión de hobbyDB ha caducado.');error.code='SESSION_EXPIRED';throw error;}if(!response.ok)throw new Error(`hobbyDB HTTP ${response.status}`);return response;}
function exactRow(item,row){const a=row?.attributes||{};const wantedName=normalize(item.character);const wantedNameTokens=tokens(wantedName);const hayName=normalize([a.name,a.variant_group_name,...(a.related_subjects||[]).map(x=>x?.name)].filter(Boolean).join(' '));const hayAll=normalize([a.name,a.aka,a.ref_number,a.variant_group_name,a.variant_details_summary,...(a.related_subjects||[]).map(x=>x?.name),...(a.series||[]).map?.(x=>x?.name)||[],...(a.brand||[]).map(x=>x?.name),...(Array.isArray(a.production_status)?a.production_status:[])].flat().filter(Boolean).join(' '));const brands=(a.brand||[]).map(x=>normalize(x?.name));const wantedNumber=String(item.popNumber||'').trim();const actualNumber=numberToken(a.ref_number);const wantedVariant=requestedVariant(item);const actualVariant=rowVariant(a);const nameHits=wantedNameTokens.filter(token=>hayName.includes(token)).length;const minNameHits=wantedNameTokens.length<=1?1:Math.max(1,Math.ceil(wantedNameTokens.length*.5));if(wantedNameTokens.length&&nameHits<minNameHits)return null;if(wantedNumber&&actualNumber!==wantedNumber)return null;if(brands.length&&!brands.includes('funko'))return null;if(wantedVariant!==actualVariant)return null;let score=0;if(normalize(a.name)===wantedName)score+=90;else score+=nameHits*30;if(wantedNumber&&actualNumber===wantedNumber)score+=120;if(brands.includes('funko'))score+=30;if(actualVariant===wantedVariant)score+=70;const category=categorySearchTerm(item.funkoCategory);if(category&&hayAll.includes(normalize(category)))score+=70;const sku=normalize(item.sku);if(sku&&hayAll.includes(sku))score+=90;return{row,score,variant:actualVariant};}
function rowUrl(row){const a=row?.attributes||{};const raw=a?.urls?.catalog_item_link_url||a?.urls?.show_url||(a.slug?`/marketplaces/hobbydb/catalog_items/${a.slug}`:'');return raw?new URL(raw,HOBBYDB).href:'';}
async function searchCatalog(query,cookie){const p=new URLSearchParams();p.set('include_cit','true');p.set('include_last_page','true');p.set('include_main_images','true');p.set('per','16');p.set('from_index','true');p.set('serializer','CatalogItemPudbSerializer');p.set('market_id','hobbydb');p.set('order[name]','created_at');p.set('order[sort]','desc');p.set('page','1');p.set('q',query);p.set('subvariants','true');p.set('grouped','false');const response=await hobbydbFetch(`/api/catalog_items?${p.toString()}`,cookie);const payload=await response.json();return Array.isArray(payload?.data)?payload.data:[];}
function urlHint(item){try{const u=new URL(item.hobbydbUrl||'');if(!['hobbydb.com','www.hobbydb.com'].includes(u.hostname))return{};const slug=u.pathname.match(/\/marketplaces\/hobbydb\/catalog_items\/([^/?#]+)/i)?.[1]||'';const q=u.searchParams.get('q')||'';return{slug,q};}catch{return{};}}
async function resolveItem(item,cookie){const wanted=requestedVariant(item);const hint=urlHint(item);const category=categorySearchTerm(item.funkoCategory);const special=wanted==='classic'?'':item.funkoVariant;const queries=[hint.q,[item.character,item.popNumber,category,special].filter(Boolean).join(' '),[item.character,category,special].filter(Boolean).join(' '),[item.character,item.sku,category].filter(Boolean).join(' '),[item.character,item.popNumber].filter(Boolean).join(' '),[item.character,category].filter(Boolean).join(' '),[item.character,special].filter(Boolean).join(' '),String(item.character||'').trim(),String(item.sku||'').trim(),String(item.popNumber||'').trim()].map(x=>String(x||'').trim()).filter(Boolean);const unique=[...new Set(queries)];const seen=new Map();for(const query of unique){let rows=[];try{rows=await searchCatalog(query,cookie);}catch(error){if(error?.code==='SESSION_EXPIRED')throw error;continue;}for(const row of rows){if(row?.id&&!seen.has(String(row.id)))seen.set(String(row.id),row);}const exact=[...seen.values()].map(row=>exactRow(item,row)).filter(Boolean);if(exact.length){exact.forEach(x=>{if(hint.slug&&rowUrl(x.row).includes(`/catalog_items/${hint.slug}`))x.score+=150;});exact.sort((a,b)=>b.score-a.score);const best=exact[0];const a=best.row.attributes||{};return{id:String(best.row.id||a.id),url:rowUrl(best.row),title:a.name||item.character,variant:best.variant,searchEstimatedValue:Number(a.estimated_value)||null};}}
 throw new Error('No se encontró una ficha de hobbyDB que coincida exactamente con personaje, línea y variante.');}
async function readPriceGuide(catalogItemId,cookie){const response=await hobbydbFetch(`/api/price_guide?catalog_item_id=${encodeURIComponent(catalogItemId)}`,cookie);const payload=await response.json();const attributes=payload?.data?.[0]?.attributes;const amount=Number(attributes?.estimated_value);if(!Number.isFinite(amount)||amount<=0)return null;return{amount,currency:'USD',timestamp:attributes?.timestamp||null,calculatedFor:attributes?.calculated_for||null};}
function configuredOrigins(){const values=String(process.env.APP_ORIGIN||'').split(',').map(x=>x.trim().replace(/\/$/,'')).filter(Boolean);return new Set(['https://frikivault-alvarioto-2026.web.app','https://frikivault-alvarioto-2026.firebaseapp.com',...values]);}
function applyCors(req,res){const origin=String(req.headers.origin||'').replace(/\/$/,'');if(!origin)return true;const allowed=configuredOrigins();if(!allowed.has(origin))return false;res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Vary','Origin');res.setHeader('Access-Control-Allow-Headers','Content-Type');res.setHeader('Access-Control-Allow-Methods','POST, OPTIONS');res.setHeader('Access-Control-Max-Age','86400');return true;}
export default async function handler(req,res){if(!applyCors(req,res))return json(res,403,{error:'Origen no autorizado.'});if(req.method==='OPTIONS')return res.status(204).end();if(req.method!=='POST')return json(res,405,{error:'Método no permitido.'});try{const cookie=String(process.env.HOBBYDB_COOKIE||'').trim();if(!cookie)return json(res,503,{error:'La sesión de hobbyDB no está configurada.'});const body=typeof req.body==='string'?JSON.parse(req.body):(req.body||{});const item=body.item||{};if(!item.character)return json(res,400,{error:'Falta el personaje o nombre del Funko.'});if(item.popNumber&&!/^\d{1,5}$/.test(String(item.popNumber)))return json(res,400,{error:'El número Pop no es válido.'});const match=await resolveItem(item,cookie);const guide=await readPriceGuide(match.id,cookie);const fallback=Number(match.searchEstimatedValue);const amount=guide?.amount||(Number.isFinite(fallback)&&fallback>0?fallback:null);if(!amount)return json(res,404,{error:'Sin valor publicado en hobbyDB.'});return json(res,200,{status:'completed',value:{amount,currency:'USD',url:match.url,evidence:`Estimated Value $${amount}`,variant:variantLabel(match.variant),title:match.title,catalogItemId:match.id,timestamp:guide?.timestamp||null,calculatedFor:guide?.calculatedFor||null}});}catch(error){const message=String(error?.message||'No se pudo leer hobbyDB.');const status=error?.code==='SESSION_EXPIRED'?401:502;return json(res,status,{error:message});}}
